Add array route support
dingo/api pull request #1693
Opened 2019-12-20 12:57 UTC by faytekin

To have more readable codes, small changes have been done. In Route, Controller names are given as arrays.

Example
```php
use App\Api\V1\Controllers\LoginController;
$api->post('login', [LoginController::class, 'login']);
```

2019-12-20 13:06 UTC, taliptako commented
@jasonlew @specialtactics Can you please merge this?

2020-01-03 03:21 UTC, specialtactics commented
Sorry, but I don't agree that this is more readable - it creates ambiguity because it is not clear what those array elements mean and what they relate to.

It is also not the way documented on the Laravel docs.

2020-01-03 13:48 UTC, faytekin commented
I think there has been a misunderstanding. You can set a route in this way at @specialtactics Laravel's own router. But this feature does not exist in Dingo API. I made it as an option. It does not break the current router. Anyone may use or just continue the current one.

2020-01-05 04:09 UTC, specialtactics requested changes

2020-01-05 04:09 UTC, specialtactics commented on src/Routing/Router.php
> +        } elseif (is_array($action)) {
Can you just add a comment here,

```php
// For this sort of syntax $api->post('login', [LoginController::class, 'login']);
```

2020-01-05 04:10 UTC, specialtactics commented
Hey @faytekin that's fine in that case, I just requested one change which is to put a comment donoting what the code does.

Also there is a merge conflict with that file which you need to resolve.

2020-01-06 12:31 UTC, specialtactics approved these changes

2020-01-06 12:31 UTC, merged

2020-01-06 12:36 UTC, specialtactics commented
Merged, tagged